### ISSUE TITLE
Feature: Octoprint plugin

### ISSUE THREAD

**Issue by kenjiqq** [ff8jake/g81-to-heatmap#3]
This seems like it would be amazing as a Octoprint plugin
I'm very new to Octoprint so i don't really know what you can do with the plugin system but I assume this would be possible. 

Trigger the bed leveling and then display the heatmap right in octoprint. 

Just wanted to leave the idea here.

**Comment by TheBrigandier** [comment]
Been slacking on getting Octoprint set up on my machine, but have used it in the past. Will see about getting it set up tonight and investigate if this is possible.

**Comment by TheBrigandier** [comment]
@kenborge https://github.com/ff8jake/OctoPrint-PrusaMeshMap - testers appreciated. Prusa forum thread here: https://shop.prusa3d.com/forum/original-prusa-i3-mk3-f30/-help-needed-octoprint-prushmeshmap-plugin-t15333.html

**Comment by kenjiqq** [comment]
Awesome, will try it out tonight
